### PR TITLE
Added Carousel section with AvatarCarousel

### PR DESCRIPTION
**Pull request by epoll31**
## Description

Added Carousel section to site with AvatarCarousel as first example

## Proposed Changes

- Added new `carousel` folder to showcase
  - I also added the `src/showcase/components/carousel/AvatarCarousel.tsx` file which contains the new component
- Added `CarouselCards` to `ui-group` 
- Added a carousel card in `src/showcase/ui-group/ComponentCards.tsx`
- Added docs page `src/app/(docs)/components/carousel/page.mdx` that loads the `CarouselCards`
- Added `Carousel` to `src/components/Navigation.tsx` to link to new page
- Added to `credits.md`

## Screenshots

https://github.com/SyntaxUI/syntaxui/assets/16091805/fa192d61-c34e-419f-913d-b8c9f9cb0e70

## Checklist

Please check the boxes that apply:

- [x] I have rebased my branch on top of the latest `main` branch.
- [x] I have tested the changes locally
- [x] I ran `npm run build` and build is successful
- [x] I have added necessary documentation (if applicable)
- [x] I have updated the credits.md file (if applicable)

### CODE REVIEW

**Comment by Ansub** [comment]
This will actually go under Testimonial section

**Comment by epoll31** [comment]
@Ansub 
> This will actually go under Testimonial section

Would you like me to create the Testimonial Section?
Converting the current individual testimonial to a group like I did for the carousels?

**Comment by Ansub** [comment]
add it on top of testiomonial cards like we have added for [features sections](https://syntaxui.com/components/features)

**Comment by epoll31** [comment]
Should be good now :)

Screenshot 2024-06-03 at 9 06 59 AM

**Pull request merged**
