### PR TITLE
fix : responsive issue in code component

### PR DESCRIPTION
**Pull request by N4J13**
Fix mobile responsiveness issue in code component

This pull request addresses an issue where the code is overflowing on mobile devices.

Changes
Adjusted tailwind utility classes to prevent code preview content from overflowing the page on smaller screens.
Attached screenshots:

Before: [Link](https://github.com/SyntaxUI/syntaxui/assets/44539538/a9f68cd6-2ed1-4d48-b1a0-57b0214da364)

### CODE REVIEW

**Comment by N4J13** [comment]
After fixing the issue: 
WhatsApp Image 2024-06-22 at 22 53 57_4588aede

**Comment by epoll31** [comment]
Good catch, can you also make sure that the `Copy` button stays in the right corner? In your after photo, it seems to be in the left corner.

**Comment by N4J13** [comment]
didn't noticed that at first time . should be fixed by now.

**Comment by Ansub** [comment]
Awesome catch @N4J13!

**Pull request merged**
